### ISSUE TITLE
Landscape

### ISSUE THREAD

**Issue by PieterVO** [smooch/smooch-ios-rich-notifications#4]
In landscape mode, the "Reply" bar with the text field is not the correct width (I guess, it's the width of the device in portrait mode).

If you want, I can provide a screenshot.

**Comment by mspensieri** [comment]
Hmm this bar is actually rendered by the OS, not by us. We simply specify a `UNTextInputNotificationAction` and register it with a `UNNotificationCategory`; sizing and placement of the input is entirely out of our hands at that point 😕

**Comment by PieterVO** [comment]
Thank you for your answer!
